---
version: "3"

vars:
  LINE_LENGTH: 80

tasks:
  default:
    - task: watch

  up:
    desc: Runs nix-shell and task runner. Assumes taskfile installed locally.
    cmd: nix-shell --run "task"

  freeze:
    desc: Freeze requirements.
    cmd: pip freeze --all > requirements.txt

  lint:
    desc: Lint code.
    cmd: black -l {{.LINE_LENGTH}} .

  test:
    desc: Run unit tests.
    cmds:
      - pytest --mypy .

  upgrade:
    desc: Upgrade requirements.
    cmd: pip install --upgrade -r requirements.in

  watch:
    desc: Run test watcher.
    cmd: ptw --onpass "task lint" -- --mypy
    interactive: true

