---
version: "3"

vars:
  LINE_LENGTH: 80

tasks:
  default:
    - task: watch

  up:
    desc: Runs nix-shell and task runner. Assumes taskfile installed locally.
    cmds:
      - nix-shell --run "task"

  freeze:
    desc: Freeze requirements.
    cmds:
      - pip freeze --all > requirements.txt

  lint:
    desc: Lint code.
    cmds:
      - black -q -l {{.LINE_LENGTH}} .

  test:
    desc: Run unit tests.
    cmds:
      - pytest --mypy .

  upgrade:
    desc: Upgrade requirements.
    cmds:
      - pip install --upgrade -r requirements.in

  watch:
    desc: Run test watcher.
    cmds:
      - ptw --beforerun "task lint" -- --mypy
    interactive: true
